# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b0d471e63f2e0270f103d08ba1e7022bc73a26a746da131c10f29120259eb02a9e594da06a56dc81b58492262f246778e27471c90f3b903670cea8d0b37373

test:
  secret_key_base: c3e82b0bc2f7d6cba1ef08af637bd17eefd9d6488f659036e4c80686d47c9bd8c46c63a1edf9d013840651e8b0273a5c01928ec85102d6af666069c56c07910e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
